name: Update Feed
# on:
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]
on:
  workflow_dispatch:
jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
        cache: 'pip'
    - name: Run check of pwd
      run: pwd
    - name: Run check of what's in pwd
      run: ls
    - name: Run update script
      run: python ./src/update_feed.py
    - name: commit updates (if available)
      run: git status
    - name: stage changed files
      run: |
        git add .
        if [ -z "$(git status --porcelain)" ]; then
          echo "No changes to commit"
          exit 0
        fi
        git commit -m "new update"
        git remote set-url origin https://<username>:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
        git push origin main
    # - name: fetch from master
    #   run: git fetch origin master
    # - name: push code to master
    #   run: git push origin main
      
    # - name: Install dependencies
    #   run: |
    #     python -m pip install --upgrade pip
    #     pip install flake8 pytest
    #     if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    # - name: Lint with Ruff
    #   run: |
    #     pip install ruff
    #     ruff --output-format=github .
    # - name: Test with pytest
    #   run: |
    #     pytest
